/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matrices.y.tarea.pkg4;

import javax.swing.*;
/**
 *
 * @author Alberto Arroyo
 */
public class Tarea_4_versión_formulario extends javax.swing.JFrame {
    public boolean validor=true;public int [][] m1 = new int [3][3];public int [][] m2 = new int [3][3];public int [][] m3 = new int [3][3];public int val=0;
    public boolean validor2;public boolean validor3;public boolean validor4=false;
    /**
     * Creates new form Tarea_4_versión_formulario
     */
    public Tarea_4_versión_formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p0 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        op = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        ma = new javax.swing.JRadioButton();
        mb = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUMA, RESTA O MULTIPLICACIÓN DE MATRICES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("POSICIÓN (0,0):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("POSICIÓN (0,1):");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("POSICIÓN (0,2):");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("POSICIÓN (1,0):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("POSICIÓN (1,1):");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("POSICIÓN (1,2):");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("POSICIÓN (2,0):");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("POSICIÓN (2,1):");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("POSICIÓN (2,2):");

        p0.setEditable(false);

        p1.setEditable(false);

        p2.setEditable(false);

        p3.setEditable(false);

        p4.setEditable(false);

        p5.setEditable(false);

        p6.setEditable(false);

        p7.setEditable(false);

        p8.setEditable(false);

        op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUMA", "RESTA", "MULTIPLICACIÓN" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("OPERACIÓN:");

        nuevo.setBackground(new java.awt.Color(0, 204, 0));
        nuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuevo.setText("NUEVO");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(51, 204, 255));
        guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("GUARDAR EN MATRIZ");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 0));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("SALIR");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ma.setText("MATRIZ A");
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });

        mb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mb.setText("MATRIZ B");
        mb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ESCOGE UNA MATRIZ:");

        calcular.setBackground(new java.awt.Color(153, 0, 0));
        calcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("CALCULAR");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ma)
                .addGap(18, 18, 18)
                .addComponent(mb)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(nuevo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calcular)
                                .addGap(51, 51, 51)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(p1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ma)
                    .addComponent(mb)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if(ma.isSelected() || mb.isSelected()){
            if(p0.getText().isEmpty()||p1.getText().isEmpty()||p2.getText().isEmpty()||p3.getText().isEmpty()||
            p4.getText().isEmpty()||p5.getText().isEmpty()||p6.getText().isEmpty()||p7.getText().isEmpty()||p8.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Te falta rellenar posiciones.");
        }else{
            JTextField[] tf = {p0, p1, p2, p3, p4, p5, p6, p7, p8};
                for (int i = 0; i < tf.length; i++) {
                    String text = tf[i].getText();
                    int valor = Integer.parseInt(text);
                    if(ma.isSelected()){
                        m1[i / 3][i % 3] = valor;
                        validor2=true;
                    }if(mb.isSelected()){
                        m2[i / 3][i % 3] = valor;
                        validor3=true;
                    }
                }
                if(ma.isSelected()&&!validor3){JOptionPane.showMessageDialog(null, "Guardado correctamente. Continúa con la Matriz B.");}
                if((ma.isSelected()||mb.isSelected())&&validor2&&validor3){JOptionPane.showMessageDialog(null, "Guardado correctamente. Presiona Calcular");validor=true;}
                if(mb.isSelected()&&!validor2){JOptionPane.showMessageDialog(null, "Guardado correctamente. Continúa con la Matriz A.");}
        p0.setEditable(false);p1.setEditable(false);p2.setEditable(false);p3.setEditable(false);p4.setEditable(false);p5.setEditable(false);p6.setEditable(false);p7.setEditable(false);p8.setEditable(false);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Escoge una Matriz para comenzar.");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        // TODO add your handling code here:
        if(resultado.getText().isEmpty()){
            if(mb.isSelected()){
            val=0;
            p0.setText(null);p1.setText(null);p2.setText(null);p3.setText(null);p4.setText(null);p5.setText(null);p6.setText(null);p7.setText(null);p8.setText(null);
        }
        
        if(mb.isSelected() && validor==false){
            JOptionPane.showMessageDialog(null, "Ya se guardó la Matriz A, no se puede volver.");
            ma.setSelected(false);
        }else{
            mb.setSelected(false);
            if(validor2){
                p0.setText(null);p1.setText(null);p2.setText(null);p3.setText(null);p4.setText(null);p5.setText(null);p6.setText(null);p7.setText(null);p8.setText(null);
            }
            ma.setSelected(true);
            mb.setSelected(false);
            if(p0.getText().isEmpty()||p1.getText().isEmpty()||p2.getText().isEmpty()||p3.getText().isEmpty()||
                p4.getText().isEmpty()||p5.getText().isEmpty()||p6.getText().isEmpty()||p7.getText().isEmpty()||p8.getText().isEmpty()){
                if(val==1){
                    JOptionPane.showMessageDialog(null, "Faltan posiciones por rellenar.");
                }else{
                    if(ma.isSelected()){
                mb.setSelected(false);
                JOptionPane.showMessageDialog(null, "Rellena todas las posiciones de la Matriz A.");
                p0.setEditable(true);p1.setEditable(true);p2.setEditable(true);p3.setEditable(true);p4.setEditable(true);p5.setEditable(true);p6.setEditable(true);p7.setEditable(true);p8.setEditable(true);
                if(val==0){
                    val++;
                }
                    }
                }
        }
        }
        }else{
            JOptionPane.showMessageDialog(null, "Si deseas crear 2 nuevas matrices, presiona el botón NUEVO.");
            mb.setSelected(false);
        }
    }//GEN-LAST:event_maActionPerformed

    private void mbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbActionPerformed
        // TODO add your handling code here:
        if(resultado.getText().isEmpty()){
            if(ma.isSelected()){
            val=0;
        }
        mb.setSelected(true);
        if (mb.isSelected()){
            ma.setSelected(false);
            if(val==0){
                p0.setText(null);p1.setText(null);p2.setText(null);p3.setText(null);p4.setText(null);p5.setText(null);p6.setText(null);p7.setText(null);p8.setText(null);
            }
            if(p0.getText().isEmpty()||p1.getText().isEmpty()||p2.getText().isEmpty()||p3.getText().isEmpty()||
                p4.getText().isEmpty()||p5.getText().isEmpty()||p6.getText().isEmpty()||p7.getText().isEmpty()||p8.getText().isEmpty()){
                if(val==1){
                    JOptionPane.showMessageDialog(null, "Faltan posiciones por rellenar.");
                }else{
                    if(mb.isSelected()){
                        ma.setSelected(false);
                        JOptionPane.showMessageDialog(null, "Rellena todas las posiciones de la Matriz B.");
                        p0.setEditable(true);p1.setEditable(true);p2.setEditable(true);p3.setEditable(true);p4.setEditable(true);p5.setEditable(true);p6.setEditable(true);p7.setEditable(true);p8.setEditable(true);
                        if(val==0){
                            val++;
                        }
                            }
                        }
            }
        }
        }else{
            JOptionPane.showMessageDialog(null, "Si deseas crear 2 nuevas matrices, presiona el botón NUEVO.");
            ma.setSelected(false);
        }
    }//GEN-LAST:event_mbActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        ma.setSelected(false);mb.setSelected(false);
        resultado.setText(null);p0.setText(null);p1.setText(null);p2.setText(null);p3.setText(null);p4.setText(null);p5.setText(null);p6.setText(null);p7.setText(null);p8.setText(null);
        m1 = new int [3][3];
        m2 = new int [3][3];
        val=0;validor=true;validor2=false;validor3=false;
    }//GEN-LAST:event_nuevoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        if(validor){
            if(op.getSelectedItem().equals("SUMA")){
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    m3[i][j]=m1[i][j]+m2[i][j];
                }
            }
        }else{if(op.getSelectedItem().equals("RESTA")){
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    m3[i][j]=m1[i][j]-m2[i][j];
                }
            }
        }else{if(op.getSelectedItem().equals("MULTIPLICACIÓN")){
            int row = m1.length;
            int cola = m1[0].length;
            int colb = m2[0].length;
            for (int i = 0; i < row; i++) {
                for (int j = 0; j < colb; j++) {
                    int sum = 0;
                    for (int k = 0; k < cola; k++) {
                        sum += m1[i][k] * m2[k][j];
                    }
                    m3[i][j] = sum;
                }
            }
        }}}
        for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    if(m3[i][j]==m1[i][j]||m3[i][j]==m2[i][j]){
                        validor4=true;
                    }
                }
            }
        if(validor4){
            JOptionPane.showMessageDialog(null, "En una de ambas matrices no colocaste nada, así que se considerará como 0.");
            }
        if (resultado.getText().isEmpty()){
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    String valor = String.format("%3d ", m3[i][j]);
                    resultado.append(valor);
                }
                resultado.append("\n");
            }
        }else{
            resultado.setText(null);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Te falta rellenar datos.");
        }
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarea_4_versión_formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarea_4_versión_formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarea_4_versión_formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarea_4_versión_formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarea_4_versión_formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JButton exit;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ma;
    private javax.swing.JRadioButton mb;
    private javax.swing.JButton nuevo;
    private javax.swing.JComboBox<String> op;
    private javax.swing.JTextField p0;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
